### ISSUE TITLE
Volumio incompatibility

### ISSUE THREAD

**Issue by DucLeto51** [ahaack/onkyo-rpi#1]
I try to use onkyo-rpi to control my receiver with a raspberry 1 B playing music with Volumio.
When I send command to receiver (volume up), music stop playing on Volumio.
When I push play button again on volumio, music restart but speed is wrong (very slow).
I've tried to start pigpiod with -t 0 option but result is the same.
Do you have an idea to fix this issue ?

**Comment by ahaack** [comment]
Sorry for the late response. Can you provide more information/logs concerning the problem. Actually I don't think there is a direct connection between the described problem and the scripts provided in this repository.

**Comment by ahaack** [comment]
cannot reproduce
