### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by westonmiller** [ahaack/onkyo-rpi#2]
What is the best way to troubleshoot this, I don't have a oscilloscope.  I have check that my gpis pins are all working.  I have a stereo headphone jack, with both left and right connected to the gpio pin and the ground connected properly. But I'm not getting any commands to work, I ran the scan.py for every possible message with no response from my Onkyo TX-SR605.
Any help would be appreciated.

**Comment by ahaack** [comment]
I think your wiring is not correct. If you are using a stereo jack, make sure that only the tip is connected to the GPIO port. The second segment for the other audio channel and the ground segment should be connected to ground, I guess. Also make sure you are connected to the correct GPIO port.

**Comment by westonmiller** [comment]
I think that was the issue, I found an old mono plug and used it and everything works now, thanks.
